### PR TITLE
Drop Fedora 31 configuration

### PR DESCRIPTION
**Pull request by StykMartin**

### CODE REVIEW

**Review by renanrodrigo — APPROVED** [review]
lgtm

**Review by cbouchar — APPROVED** [review]
TY

**Comment by StykMartin** [comment]
Any plans for merge?

**Comment by cbouchar** [comment]
I'm trying to get another release of restraint out.  It's failing to build f34 due to a bug in a library.  Once this is resolved, I'll merge this in.  TY for reminding me.

**Pull request merged**
