### PR TITLE
chore: use `$releasever` in RPM GPG key to download

### LINKED ISSUE #43: Use $releasever YUM variable before building EL8 repository
At the moment EPEL GPG key is hardcoded to point to EPEL 7 GPG key in YUM repository definition. This is not a problem at the moment, but if we decide to build an EL8 repository this will be a problem.

_Originally posted by @StykMartin in https://github.com/beaker-project/beaker-project.org/pull/42#discussion_r1364243098_

### PR DESCRIPTION
**Pull request by JohnVillalovos**
Closes: #43

### CODE REVIEW

**Comment by JohnVillalovos** [comment]
@StykMartin for your review 🙂

**Comment by JohnVillalovos** [comment]
Not sure if this content automatically gets pushed out to the website or if it has to be manually done.

**Comment by StykMartin** [comment]
We had Jenkins to do this kind of magic... Jenkins is gone so I will rebuild the build pipeline in GitHub Actions. For now.. manual effort it is.

**Comment by JohnVillalovos** [comment]
> We had Jenkins to do this kind of magic... Jenkins is gone so I will rebuild the build pipeline in GitHub Actions. For now.. manual effort it is.

If you need any assistance, please let me know. I can try to find some free time.

**Comment by StykMartin** [comment]
Sure I will let you know. I'm planning to do that because I need CI to build things for the new release. So yeah

**Review by StykMartin — APPROVED** [review]

**Pull request merged**
